Use “var” rather than “let”
Something(?) introduces an error here,
        let trampoline = function(values){
        ^^^
SyntaxError: Unexpected strict mode reserved word

For now, just using “var” works.