Fix error handling on wrongly formatted `deftype`
For example, like `(deftype f 23)`

Now it shows

  ERROR: `23' is not a list.

instead of accepting it.